begin;
drop table if exists xactivos cascade;
drop table if exists reubicaciones_activo cascade;
drop table if exists bajas_activo cascade;
drop table if exists activos_imagenes cascade;
drop table if exists activos cascade;
drop table if exists folio_activos cascade;
-- drop table if exists xtipos_activo cascade;
-- drop table if exists tipos_activo cascade;
-- drop table if exists folio_contable cascade;
-- drop table if exists centros_costo cascade;
-- drop table if exists departamentos cascade;
-- drop table if exists clasificaciones cascade;
-- drop table if exists movimientos cascade;
-- drop table if exists transacciones cascade;
-- drop table if exists polizas cascade;
-- drop table if exists auxiliares cascade;
-- drop table if exists cuentas cascade;
-- drop table if exists mayores cascade;
-- drop table if exists niveles cascade;
-- drop table if exists libro cascade;
-- drop table if exists libros cascade;
-- drop table if exists ejercicios cascade;
-- drop table if exists xauxiliares cascade;
-- drop table if exists xcentros_costo cascade;
-- drop table if exists xcuentas cascade;
-- drop table if exists xejercicios cascade;
-- drop table if exists xlibros cascade;
-- drop table if exists xmovimientos cascade;
-- drop table if exists xniveles cascade;
-- drop table if exists xtransacciones cascade;
-- drop table if exists empleados cascade;
-- alter table empresas drop column cuenta_id;
-- drop table if exists resultados cascade;
commit;