begin;
-- alter table activos  alter column depreciacion_fecha drop not null;
-- alter table xactivos alter column depreciacion_fecha drop not null;
-- alter table activos  add constraint activo_codigo_idx unique (codigo);
-- create unique index activo_codigo_idx on activos (codigo);
drop table if exists xactivos cascade;
drop table if exists reubicaciones_activo cascade;
drop table if exists bajas_activo cascade;
drop table if exists activos_imagenes cascade;
drop table if exists activos cascade;
drop table if exists folio_activos cascade;
commit;